[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm ci --include=dev && npx prisma generate && npx prisma db push --force-reset && npm run build"]

[start]
cmd = "cd server && node dist/index.js"
